---
- hosts: "{{host | default ('thelinux')}}"
  vars_files: 
    - /mnt/c/Users/{{ lookup('env','USER' )}}/apikeys/mqvariables.enc
  vars:
    srcdir: /mnt/c/Users/{{ lookup('env','USER' )}}/OneDrive/dev/tackley/radio
    destdir: "{{ ansible_env.HOME }}/src/tackley-tools"
    logdir: "{{ ansible_env.HOME }}/logs"
  tasks:
  - name: Copy supporting files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/checkAndAlertRadio.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/sendRadioAlert.py', dest: '{{destdir}}/', mode: '644', backup: no }

  - name: update LOGDIR in pythoncode
    ansible.builtin.replace:
      path: '{{destdir}}/sendRadioAlert.py'
      regexp: "LOGDIR"
      replace: "{{ logdir }}"

  - name: update MQ broker
    ansible.builtin.replace:
      path: '{{destdir}}/checkAndAlertRadio.sh'
      regexp: "broker"
      replace: "wxsatpi"

  - name: update mquser
    ansible.builtin.replace:
      path: '{{destdir}}/checkAndAlertRadio.sh'
      regexp: "mquser"
      replace: "sensors"

  - name: update mqpass
    ansible.builtin.replace:
      path: '{{destdir}}/checkAndAlertRadio.sh'
      regexp: "mqpass"
      replace: "{{ mqsenspassword }}"
